# Generated by Django 3.0.3 on 2020-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_auto_20200208_0531'), ('inventory', '0003_auto_20200208_0538'), ('inventory', '0004_item_listing_date'), ('inventory', '0005_auto_20200208_0551'), ('inventory', '0006_auto_20200208_1723')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Date item was purchased')),
                ('purchase_price', models.DateField(blank=True, null=True, verbose_name='Date item was sold')),
                ('purchased_from', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Date item was purchased')),
                ('purchase_price', models.PositiveIntegerField(blank=True, help_text='include sales tax if any', null=True)),
                ('purchased_from', models.CharField(choices=[('goodwill', 'Goowill'), ('ecothrift', 'Ecothrift'), ('salvation_army', 'Salvation Army'), ('cvs', 'CVS'), ('ebay', 'Ebay'), ('amazon', 'Amazon'), ('tj_maxx', 'TJ Maxx'), ('marshalls', 'Marshalls'), ('ross', 'Ross'), ('dollar_tree', 'Dollar Tree'), ('poshmark', 'Poshmark'), ('other', 'Other')], default='goodwill', max_length=24)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('meta', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('shoes', 'Shoes')], default='', max_length=24, null=True)),
                ('listing_date', models.DateField(blank=True, help_text='To calculate sell through rate', null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('open_box', 'Open Box'), ('like_new', 'Like New'), ('good', 'Good'), ('used', 'Used')], default='new', max_length=24, null=True)),
            ],
        ),
    ]
