# Generated by Django 3.0.3 on 2020-02-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200208_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='listing_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='purchased_from',
            field=models.CharField(choices=[('goodwill', 'Goowill'), ('ecothrift', 'Ecothrift'), ('salvation_army', 'Salvation Army'), ('cvs', 'CVS'), ('ebay', 'Ebay'), ('amazon', 'Amazon'), ('tj_maxx', 'TJ Maxx'), ('marshalls', 'Marshalls'), ('ross', 'Ross'), ('dollar_tree', 'Dollar Tree'), ('bulq', 'Bulq'), ('source', 'Source Liquidations'), ('via', 'Via Trading'), ('poshmark', 'Poshmark'), ('other', 'Other')], default='goodwill', max_length=24),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='average per item'),
        ),
    ]
