# Generated by Django 3.0.3 on 2020-02-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200208_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
    ]
