# Generated by Django 3.0.3 on 2020-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200208_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchased_from',
            field=models.CharField(choices=[('goodwill', 'Goowill'), ('ecothrift', 'Ecothrift'), ('salvation_army', 'Salvation Army'), ('cvs', 'CVS'), ('mercari', 'Mercari'), ('ebay', 'Ebay'), ('amazon', 'Amazon'), ('tj_maxx', 'TJ Maxx'), ('marshalls', 'Marshalls'), ('ross', 'Ross'), ('dollar_tree', 'Dollar Tree'), ('bulq', 'Bulq'), ('source', 'Source Liquidations'), ('via', 'Via Trading'), ('poshmark', 'Poshmark'), ('etsy', 'Etsy'), ('other', 'Other')], default='goodwill', max_length=24),
        ),
    ]
