# Generated by Django 3.0.3 on 2020-02-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200208_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='purchased_from',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchased_from',
        ),
    ]
