# Generated by Django 3.0.3 on 2020-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sales_tax', models.FloatField(blank=True, help_text='Do you pay sales tax to purchase here?', null=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
