# Generated by Django 3.0.3 on 2020-02-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_auto_20200208_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateField(blank=True, help_text='To calculate sell through rate', null=True)),
                ('sale_price', models.PositiveIntegerField(blank=True, help_text='total price including shipping', null=True)),
                ('sale_fees', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_fees', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Date item was sold')),
                ('sold_at', models.CharField(blank=True, choices=[('goodwill', 'Goowill'), ('ecothrift', 'Ecothrift'), ('salvation_army', 'Salvation Army'), ('cvs', 'CVS'), ('ebay', 'Ebay'), ('amazon', 'Amazon'), ('tj_maxx', 'TJ Maxx'), ('marshalls', 'Marshalls'), ('ross', 'Ross'), ('dollar_tree', 'Dollar Tree'), ('bulq', 'Bulq'), ('source', 'Source Liquidations'), ('via', 'Via Trading'), ('poshmark', 'Poshmark'), ('other', 'Other')], default='', max_length=24, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
    ]
