# Generated by Django 3.0.3 on 2020-02-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('orders', '0001_initial'), ('orders', '0002_auto_20200208_1744'), ('orders', '0003_auto_20200208_1826')]

    initial = True

    dependencies = [
        ('inventory', '0007_auto_20200208_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateField(blank=True, help_text='To calculate sell through rate', null=True)),
                ('sale_price', models.FloatField(blank=True, help_text='total price including shipping', null=True)),
                ('sale_fees', models.FloatField(blank=True, null=True)),
                ('shipping_fees', models.FloatField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Date item was sold')),
                ('sold_at', models.CharField(blank=True, choices=[('goodwill', 'Goowill'), ('ecothrift', 'Ecothrift'), ('salvation_army', 'Salvation Army'), ('cvs', 'CVS'), ('mercari', 'Mercari'), ('ebay', 'Ebay'), ('amazon', 'Amazon'), ('tj_maxx', 'TJ Maxx'), ('marshalls', 'Marshalls'), ('ross', 'Ross'), ('dollar_tree', 'Dollar Tree'), ('bulq', 'Bulq'), ('source', 'Source Liquidations'), ('via', 'Via Trading'), ('poshmark', 'Poshmark'), ('etsy', 'Etsy'), ('other', 'Other')], default='', max_length=24, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('collected_tax', models.FloatField(blank=True, help_text='Did this marketplace collect sales tax on your behalf?', null=True)),
                ('item_number', models.PositiveIntegerField(blank=True, help_text='For eBay', null=True)),
                ('order_id', models.PositiveIntegerField(blank=True, help_text='For eBay', null=True)),
                ('promoted', models.BooleanField(blank=True, help_text='Did this item sell due to paid advertising?', null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_method', models.CharField(choices=[('first_class', 'USPS First Class'), ('priority', 'USPS Priority')], default='first_class', max_length=24)),
                ('tracking_number', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_id', models.PositiveIntegerField(blank=True, help_text='For eBay', null=True)),
                ('type', models.CharField(choices=[('domestic', 'Domestic'), ('inernational', 'International')], default='domestic', max_length=24)),
            ],
        ),
    ]
