# Generated by Django 3.0.3 on 2020-02-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_squashed_0003_auto_20200208_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sold_at',
        ),
    ]
