# Generated by Django 3.0.3 on 2020-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_price',
            field=models.FloatField(blank=True, help_text='total price including shipping', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
