# Generated by Django 3.0.3 on 2020-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200208_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_tax',
            field=models.FloatField(blank=True, help_text='Did this marketplace collect sales tax on your behalf?', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_number',
            field=models.PositiveIntegerField(blank=True, help_text='For eBay', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, help_text='For eBay', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='promoted',
            field=models.BooleanField(blank=True, help_text='Did this item sell due to paid advertising?', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('first_class', 'USPS First Class'), ('priority', 'USPS Priority')], default='first_class', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(blank=True, help_text='For eBay', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('inernational', 'International')], default='domestic', max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='sold_at',
            field=models.CharField(blank=True, choices=[('goodwill', 'Goowill'), ('ecothrift', 'Ecothrift'), ('salvation_army', 'Salvation Army'), ('cvs', 'CVS'), ('mercari', 'Mercari'), ('ebay', 'Ebay'), ('amazon', 'Amazon'), ('tj_maxx', 'TJ Maxx'), ('marshalls', 'Marshalls'), ('ross', 'Ross'), ('dollar_tree', 'Dollar Tree'), ('bulq', 'Bulq'), ('source', 'Source Liquidations'), ('via', 'Via Trading'), ('poshmark', 'Poshmark'), ('etsy', 'Etsy'), ('other', 'Other')], default='', max_length=24, null=True),
        ),
    ]
