# Generated by Django 3.0.3 on 2020-02-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
        ('orders', '0003_order_sold_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sold_marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaces.Marketplace'),
        ),
    ]
